Han-Yip-Man/Han-Yip-Man-back

src/main/java/com/supercoding/hanyipman/entity/Address.java, src/main/java/com/supercoding/hanyipman/entity/Buyer.java, src/main/java/com/supercoding/hanyipman/entity/BuyerCoupon.java, src/main/java/com/supercoding/hanyipman/entity/Cart.java, src/main/java/com/supercoding/hanyipman/entity/CartOptionItem.java, src/main/java/com/supercoding/hanyipman/entity/Category.java, src/main/java/com/supercoding/hanyipman/entity/Coupon.java, src/main/java/com/supercoding/hanyipman/entity/Menu.java, src/main/java/com/supercoding/hanyipman/entity/MenuGroup.java, src/main/java/com/supercoding/hanyipman/entity/Option.java, src/main/java/com/supercoding/hanyipman/entity/OptionItem.java, src/main/java/com/supercoding/hanyipman/entity/Order.java, src/main/java/com/supercoding/hanyipman/entity/Payment.java, src/main/java/com/supercoding/hanyipman/entity/Review.java, src/main/java/com/supercoding/hanyipman/entity/Seller.java, src/main/java/com/supercoding/hanyipman/entity/Shop.java, src/main/java/com/supercoding/hanyipman/entity/User.java
=> Init: 엔티티 생성

src/main/resources/application.yml
=> Chore: rds 주소 변경

src/main/java/com/supercoding/hanyipman/entity/Address.java, src/main/java/com/supercoding/hanyipman/entity/Category.java, src/main/java/com/supercoding/hanyipman/entity/Menu.java, src/main/java/com/supercoding/hanyipman/entity/MenuGroup.java, src/main/java/com/supercoding/hanyipman/entity/Order.java, src/main/java/com/supercoding/hanyipman/entity/Payment.java, src/main/java/com/supercoding/hanyipman/entity/Review.java, src/main/java/com/supercoding/hanyipman/entity/Shop.java, src/main/java/com/supercoding/hanyipman/entity/User.java
1. 결제내역에서 사장님과 유저 추가
2. 메뉴와 대분류에서 노출 순서 추가 (sequnce)
3. 회원쿠폰함 사용여부 컬럼
4. 주문 테이블에 소비자 연결
5. 주문 테이블에 주소 연결
6. 주문 테이블에 가게 연결
7. 배달 테이블 소비자, 가게 id not null -> null로
8. 배달 테이블 기본 배달지 설정 칼럼 추가
9. created_at, updated_at에 어노테이션 추가
=> Refactor: 수정한 erd에 맞게 엔티티 수정

src/main/resources/application.yml
=> Chore: rds 주소 원복

src/main/java/com/supercoding/hanyipman/config/CORSFilter.java
민승님 결제 테스트 중 CORS에러를 만나 긴급 추가하였습니다.
=> feat(CORS): CORS 긴급도입

src/main/java/com/supercoding/hanyipman/config/security/SecurityConfig.java, src/main/java/com/supercoding/hanyipman/controller/MyInfoController.java, src/main/java/com/supercoding/hanyipman/controller/TokenTestController.java, src/main/java/com/supercoding/hanyipman/controller/UserController.java, src/main/java/com/supercoding/hanyipman/dto/user/request/LoginRequest.java, src/main/java/com/supercoding/hanyipman/error/domain/TokenErrorCode.java, src/main/java/com/supercoding/hanyipman/security/filters/JwtAuthenticationFilter.java, src/main/java/com/supercoding/hanyipman/security/filters/JwtExceptionFilter.java
비정상적인 토큰 입력 시 시큐리티 필터 단에서 예외 처리하였습니다.
아직 컨트롤러 단에서 토큰값이 null일 때
500, null 에러는 시간이 걸려 차후 잡을 예정입니다.
=> feat: Jwt토큰 예외처리 세분화

src/main/java/com/supercoding/hanyipman/error/domain/CouponErrorCode.java, src/main/java/com/supercoding/hanyipman/service/CouponService.java
유저 검증을 구매자인지 확인하는 로직으로 변경하였습니다. 이에 따라 에러코드도 403 에러 코드로 변경하였습니다.
=> Refactor/register coupon 유저 검증 로직 변경, 에러코드 변경

src/main/java/com/supercoding/hanyipman/controller/MyInfoController.java, src/main/java/com/supercoding/hanyipman/dto/myInfo/response/MyInfoAddressResponse.java, src/main/java/com/supercoding/hanyipman/dto/myInfo/response/MyInfoResponse.java, src/main/java/com/supercoding/hanyipman/service/MyInfoService.java
마이페이지 API 호출 시 불필요한 데이터 수정 및 삭제 작업했습니다.
=> 마이페이지 출력Response 변경

src/main/java/com/supercoding/hanyipman/controller/ReviewController.java, src/main/java/com/supercoding/hanyipman/dto/reivew/request/RegisterReviewRequest.java, src/main/java/com/supercoding/hanyipman/entity/Review.java, src/main/java/com/supercoding/hanyipman/enums/FilePath.java, src/main/java/com/supercoding/hanyipman/error/domain/ReviewErrorCode.java, src/main/java/com/supercoding/hanyipman/repository/ReviewRepository.java, src/main/java/com/supercoding/hanyipman/service/CouponService.java, src/main/java/com/supercoding/hanyipman/service/ReviewService.java
=> Feature/register review 리뷰 작성 기능 api 추가

src/main/java/com/supercoding/hanyipman/controller/CartController.java, src/main/java/com/supercoding/hanyipman/dto/cart/response/OptionItemResponse.java, src/main/java/com/supercoding/hanyipman/dto/cart/response/ViewCartResponse.java, src/main/java/com/supercoding/hanyipman/dto/vo/CustomPageable.java, src/main/java/com/supercoding/hanyipman/entity/Cart.java, src/main/java/com/supercoding/hanyipman/entity/Order.java, src/main/java/com/supercoding/hanyipman/enums/Direction.java, src/main/java/com/supercoding/hanyipman/error/domain/DirectionErrorCode.java, src/main/java/com/supercoding/hanyipman/repository/CartOptionItemRepository.java, src/main/java/com/supercoding/hanyipman/repository/CartRepository.java, src/main/java/com/supercoding/hanyipman/repository/EmCartRepository.java, src/main/java/com/supercoding/hanyipman/repository/MenuRepository.java, src/main/java/com/supercoding/hanyipman/service/CartService.java
- @Query() jpql을 사용할 때 Pageable과 fetch join을 사용하면 런타임 오류가 발생 그래서 EntityManger를 이용해 Jpql로 코드 작성
19.0버전부터는 버그가 수정됨
2038년 부터 1970년로 돌아가는 문제
Timestamp -> Instant 변경
=> Feature/장바구니 조회

src/main/java/com/supercoding/hanyipman/controller/CartController.java, src/main/java/com/supercoding/hanyipman/dto/cart/request/UpdateCartRequest.java, src/main/java/com/supercoding/hanyipman/entity/Cart.java, src/main/java/com/supercoding/hanyipman/entity/Order.java, src/main/java/com/supercoding/hanyipman/error/domain/CartErrorCode.java, src/main/java/com/supercoding/hanyipman/error/domain/ShopErrorCode.java, src/main/java/com/supercoding/hanyipman/repository/OptionItemRepository.java, src/main/java/com/supercoding/hanyipman/repository/Shop/ShopRepository.java, src/main/java/com/supercoding/hanyipman/repository/cart/CartRepository.java, src/main/java/com/supercoding/hanyipman/repository/cart/EmCartRepository.java, src/main/java/com/supercoding/hanyipman/service/CartService.java
=> Feature/장바구니 수정

src/main/java/com/supercoding/hanyipman/dto/coupon/response/ViewCouponsResponse.java, src/main/java/com/supercoding/hanyipman/repository/BuyerCouponRepository.java, src/main/java/com/supercoding/hanyipman/service/CouponService.java
쿠폰 조회시 사용된 쿠폰도 함께 응답, 사용 안 된 쿠폰 먼저 정렬
=> 리팩토링 : 쿠폰 조회 시, 사용된 쿠폰도 함께 조회하도록 

src/main/java/com/supercoding/hanyipman/controller/BuyerShopController.java, src/main/java/com/supercoding/hanyipman/service/ReviewService.java
=> 가게 리뷰 별점 평균 조회 api 추가

src/main/java/com/supercoding/hanyipman/controller/CartController.java, src/main/java/com/supercoding/hanyipman/entity/Cart.java, src/main/java/com/supercoding/hanyipman/error/domain/BuyerErrorCode.java, src/main/java/com/supercoding/hanyipman/repository/cart/CartRepository.java, src/main/java/com/supercoding/hanyipman/service/CartService.java
=> Feature/장바구니 삭제

src/main/java/com/supercoding/hanyipman/controller/UserController.java, src/main/java/com/supercoding/hanyipman/error/domain/UserErrorCode.java, src/main/java/com/supercoding/hanyipman/service/UserService.java
회원가입 시 사용할 수 있는 이메일 중복확인 API 구현하였습니다.
=> feat: 회원가입 시 사용할 수 있는 이메일 중복확인 API

src/main/java/com/supercoding/hanyipman/dto/myInfo/request/SellerUpdateInfoRequest.java, src/main/java/com/supercoding/hanyipman/service/MyInfoService.java
1. 변수명 통일 변경 userNumber -> userId
2. null 체크하는것이 아닌 orElseThrow()으로 가독성
좋게 예외처리
3. 가독성이 떨어지는 로직 함수로 만들어 따로 관리
=> Feature/Seller마이페이지 수정로직 피드백 수용

src/main/java/com/supercoding/hanyipman/service/UserService.java
1. if문으로 null체크하여 예외처리 방식에서 -> 객체 null값체크하여 즉시예외처리 로직으로 변경
2. LoginErrorCode.INVALID_LOGIN 예외가 2개 있어 하나로 합쳤습니다.
=> refactor: 로그인로직 피드백수용

src/main/java/com/supercoding/hanyipman/controller/AddressController.java, src/main/java/com/supercoding/hanyipman/controller/MyInfoController.java, src/main/java/com/supercoding/hanyipman/error/domain/AddressErrorCode.java, src/main/java/com/supercoding/hanyipman/service/AddressService.java
Buyer유저가 가지고 있는 주소 중
하나의 주소를 기본주소로 설정할 수 있는 API 추가했습니다.
=> feat: Buyer기본 주소 설정API

src/main/java/com/supercoding/hanyipman/controller/CartController.java, src/main/java/com/supercoding/hanyipman/controller/OrderController.java, src/main/java/com/supercoding/hanyipman/dto/cart/request/RegisterCartRequest.java, src/main/java/com/supercoding/hanyipman/dto/cart/request/UpdateCartRequest.java, src/main/java/com/supercoding/hanyipman/dto/order/request/RegisterOrderRequest.java, src/main/java/com/supercoding/hanyipman/entity/BuyerCoupon.java, src/main/java/com/supercoding/hanyipman/entity/Cart.java, src/main/java/com/supercoding/hanyipman/entity/Order.java, src/main/java/com/supercoding/hanyipman/enums/OrderStatus.java, src/main/java/com/supercoding/hanyipman/error/domain/BuyerCouponError.java, src/main/java/com/supercoding/hanyipman/error/domain/OrderErrorCode.java, src/main/java/com/supercoding/hanyipman/repository/BuyerCouponRepository.java, src/main/java/com/supercoding/hanyipman/repository/CartOptionItemRepository.java, src/main/java/com/supercoding/hanyipman/repository/OrderRepository.java, src/main/java/com/supercoding/hanyipman/repository/cart/EmCartRepository.java, src/main/java/com/supercoding/hanyipman/service/CartService.java, src/main/java/com/supercoding/hanyipman/service/OrderService.java, src/main/java/com/supercoding/hanyipman/utils/DateUtils.java
dto 직렬화는 기본 생성자가 있어야 함 final키워드를 같이 사용함으로써 오류가 발생 final키워드를 제거
=> Feature/주문 생성

src/main/java/com/supercoding/hanyipman/error/domain/ReviewErrorCode.java, src/main/java/com/supercoding/hanyipman/repository/ReviewRepository.java, src/main/java/com/supercoding/hanyipman/service/ReviewService.java
=> Fix : 가게별 리뷰 평점 조회 버그 수정

src/main/java/com/supercoding/hanyipman/entity/Menu.java, src/main/java/com/supercoding/hanyipman/entity/MenuGroup.java, src/main/java/com/supercoding/hanyipman/repository/shop/ShopCustomRepositoryImpl.java
Menu, MenuGroup을 대상으로  Insert할 때 isDeleted false가 들어가야하는데
코드 누락이 있어 수정했습니다.
=> Fix: Insert할 때 Menu, MenuGroup isDeleted false

src/main/java/com/supercoding/hanyipman/controller/BuyerShopController.java, src/main/java/com/supercoding/hanyipman/service/ReviewService.java
=> Refactor/review average 

src/main/java/com/supercoding/hanyipman/controller/SellerShopController.java, src/main/java/com/supercoding/hanyipman/error/domain/ShopErrorCode.java, src/main/java/com/supercoding/hanyipman/repository/shop/ShopCustomRepository.java, src/main/java/com/supercoding/hanyipman/repository/shop/ShopCustomRepositoryImpl.java, src/main/java/com/supercoding/hanyipman/repository/shop/ShopRepository.java, src/main/java/com/supercoding/hanyipman/service/SellerShopService.java
=> Feat: 가게 등록 시 내가 관리중인 가게중 중복 상호명 검사, 동일 기능 하는 API 개발

src/main/java/com/supercoding/hanyipman/config/MultipartJackson2HttpMessageConverter.java, src/main/java/com/supercoding/hanyipman/controller/MenuController.java
=> Fix: 메뉴 등록 스웨거 수정을 위한 convertor 생성

src/main/java/com/supercoding/hanyipman/service/OrderService.java
fix: 소비자의 아이디와 주문건의 소비자 아이디와 일치여부 버그 수정
=> fix: 소비자의 아이디와 주문건의 소비자 아이디와 일치여부 버그 수정

src/main/java/com/supercoding/hanyipman/service/MenuService.java
=> Fix: 메뉴 등록 시 예외처리 수정

src/main/java/com/supercoding/hanyipman/entity/Buyer.java, src/main/java/com/supercoding/hanyipman/service/KakaoOauthService.java, src/main/java/com/supercoding/hanyipman/service/UserService.java, src/main/resources/application.yml
서버 주소에 맞게 키 연결 하였습니다.
메인 서버에 맞게 카카오API 키 수정
- kakaoRedirectUri을 로컬에서 서버 주소로 변경 하였습니다.
=> refactor: 카카오 API 키 변경

src/main/java/com/supercoding/hanyipman/config/websocket/WebSocketConfig.java, src/main/java/com/supercoding/hanyipman/controller/KakaoController.java
=> 웹소캣 서버 접속 확인을 위한 배포

src/main/java/com/supercoding/hanyipman/config/websocket/WebSocketConfig.java
=> fix : 소켓 서버 config 이상 수정 원래대로 복구

src/main/java/com/supercoding/hanyipman/controller/WebController.java
connect-history api fallback 버그 수정하였습니다.
- connect-history api fallback 버그 수정
- connect-history api fallback 버그 해결 코드 추가
=> fix: connect-history api fallback 버그 수정

src/main/java/com/supercoding/hanyipman/controller/KakaoController.java, src/main/java/com/supercoding/hanyipman/service/KakaoOauthService.java
- 카카오로그인 콜백 URL 수정하였습니다.
- 카카오로그인 콜백 URL 수정하였습니다.
- 
- 카카오로그인 콜백 URL 수정
=> fix: 카카오로그인 콜백 URL 수정

build.gradle, src/main/java/com/supercoding/hanyipman/controller/WebController.java
=> Re: 메인브랜치 백업 복원

src/main/java/com/supercoding/hanyipman/dto/websocket/OrderStatusMessage.java, src/main/java/com/supercoding/hanyipman/socket/SocketService.java
- 주문 상태 변경 시 응답 dto에 가게명, 주문메뉴 추가
- 서비스 메서드 변경
- dto 변경
=> Refactor : 주문 상태 변경 시 응답 dto에 가게명, 주문메뉴 추가

src/main/java/com/supercoding/hanyipman/security/filters/JwtAuthenticationFilter.java
- 쿠키 log 제거
- 쿠키 log 제거
- 쿠키 log 제거
=> Refactor 쿠키 log 제거

src/main/java/com/supercoding/hanyipman/dto/websocket/OrderStatusMessage.java, src/main/java/com/supercoding/hanyipman/socket/SocketController.java, src/main/java/com/supercoding/hanyipman/socket/SocketService.java
- 주문상태 변경시 순서 변경 로직 추가
- 주문상태 변경시 순서 변경 로직 추가( 아직 코드 정리가 안되었지만, 일단 서버부터 살려야 해서 더러운 코드로 먼저배포 진행하겠습니다.)
=> Refactor : 주문상태 변경시 순서 변경 로직 추가

src/main/java/com/supercoding/hanyipman/dto/websocket/OrderStatusMessage.java, src/main/java/com/supercoding/hanyipman/socket/SocketController.java, src/main/java/com/supercoding/hanyipman/socket/SocketService.java
- 통일성 + 불필요 로그 코드 삭제 + 응답 데이터 반환 코드 추가
- 같은 내용을 가르키는 코드 네이밍 통일성
- 불필요한 디버깅 로그 코드 삭제
- 응답 데이터 반환 코드 추가
=> Refactor : 주문 상태 변경 소켓 통신 코드

src/main/java/com/supercoding/hanyipman/dto/Shop/seller/response/ShopOrderResponse.java
- 주문 조회 시 주문 시간 created_at으로 변경
- dto 값 변경
=> 주문 조회 시 주문 시간 created_at으로 변경

src/main/java/com/supercoding/hanyipman/controller/OrderController.java, src/main/java/com/supercoding/hanyipman/dto/order/response/OrderNoticeBuyerResponse.java, src/main/java/com/supercoding/hanyipman/dto/order/response/OrderNoticeSellerResponse.java, src/main/java/com/supercoding/hanyipman/enums/EventName.java, src/main/java/com/supercoding/hanyipman/enums/PaymentProvidor.java, src/main/java/com/supercoding/hanyipman/error/domain/PaymentErrorCode.java, src/main/java/com/supercoding/hanyipman/service/OrderService.java, src/main/java/com/supercoding/hanyipman/service/PaymentService.java
- 사장님이 주문 상태를 변경하면 알림을 발생 시킬 수 있게 기능을 구현함
- 사장님이 주문 상태를 변경하면 알림을 발생 시킬 수 있게 기능을 구현함
=> Feature/주문알림 소비자

src/main/java/com/supercoding/hanyipman/controller/OrderController.java, src/main/java/com/supercoding/hanyipman/dto/order/request/RegisterOrderRequest.java, src/main/java/com/supercoding/hanyipman/service/OrderService.java
- 주문요청 입력값 변경으로인한 로직 변경
- 주문요청 입력값 변경으로인한 로직 변경
=> refacotr/주문 

src/main/java/com/supercoding/hanyipman/controller/OrderController.java, src/main/java/com/supercoding/hanyipman/dto/order/response/OrderIdResponse.java
=> refactor/주문 

src/main/java/com/supercoding/hanyipman/config/security/CorsFilterConfig.java
- http 메소드 전체 허용
- http 메소드 전체 허용
- http 메소드 전체 허용
=> fix: cors error

src/main/java/com/supercoding/hanyipman/dto/order/response/OrderNoticeBuyerResponse.java, src/main/java/com/supercoding/hanyipman/service/OrderService.java, src/main/java/com/supercoding/hanyipman/socket/SocketService.java
- 주문 상태 변경 시 주문 상태 변경 관련 정보 sse 응답 메서드 추가
- 주문 상태 변경 로직에 sse 응답 추가 
- sse응답에 payment 정보 임시 주석 처리
=> 주문 상태 변경 시 주문 상태 변경 관련 정보 sse 응답 메서드 추가

src/main/java/com/supercoding/hanyipman/service/PaymentService.java
=> Fix/shop order list 

src/main/java/com/supercoding/hanyipman/controller/CartController.java, src/main/java/com/supercoding/hanyipman/service/CartService.java, src/main/java/com/supercoding/hanyipman/service/DeliveryService.java
cursor 기반으로 한다면 size가 10으로 설정 됐을 때 담은 장바구니가 20개 면 10개 먼저 가져오고 추후에 드래그 했을 때 10개를 더 가져오는 방식이라 소비자 입장에서는 당황스러울 수 있을것 같다고 생각했습니다.
- 전체 조회로 변경
- 커서기반 장바구니 조회 -> 전체 조회
=> Refactor/전체 장바구니 조회 커서조회 -> 전체조회

src/main/java/com/supercoding/hanyipman/repository/BuyerCouponRepository.java, src/main/java/com/supercoding/hanyipman/service/CouponService.java
- 쿠폰 중복 등록 에러(다른 유저가 등록해도 등록되지 않는) 버그 수정
* 특이사항 브랜치를 옮기기가 안되어서... refactor/websocket으로 작업중이던 브랜치로올려요.. 양해부탁드려요..
=> Fix : 쿠폰 중복 등록 에러(다른 유저가 등록해도 등록되지 않는) 버그 수정

src/main/java/com/supercoding/hanyipman/HanYipManApplication.java, src/main/java/com/supercoding/hanyipman/controller/DeliveryController.java, src/main/java/com/supercoding/hanyipman/dto/order/response/OrderNoticeResponse.java, src/main/java/com/supercoding/hanyipman/enums/EventName.java, src/main/java/com/supercoding/hanyipman/service/DeliveryService.java, src/main/java/com/supercoding/hanyipman/service/OrderService.java, src/main/java/com/supercoding/hanyipman/service/PaymentService.java, src/main/java/com/supercoding/hanyipman/socket/SocketService.java
- sse 구현 기능 socket과 충돌로 socket으로 변경
- 드론 배달 주소 전달하는 sse -> socket
- 상태 변경시 주문 상태 등의 정보 전달하는 sse -> socket
=> Refactor/websocket SSE -> Socket

src/main/java/com/supercoding/hanyipman/dto/order/response/ViewOrderDetailResponse.java, src/main/java/com/supercoding/hanyipman/service/OrderService.java
=> refactor: 주문상세시 좌표 반환

src/main/java/com/supercoding/hanyipman/service/OrderService.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> fix: pyament 누락

src/main/java/com/supercoding/hanyipman/config/security/CorsFilterConfig.java, src/main/java/com/supercoding/hanyipman/service/OrderService.java
- sse8088포트 cors접속 문제가 있었다.
- 기본8080포트 이외에 8088포트도 받을 수 있게 수정하였습니다.
=> Dev8088포트 받을 수 있게 수정 후 배포
